[package]
name = "wizardwars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.20"
anyhow = "1"
winit = "0.30"
tokio = { version = "1", features = ["full"] }
bytemuck = { version = "1",  features = [ "derive" ] }
log = "0.4"
cgmath = "0.18"
simple_logger = "4"
gltf = "1"
percent-encoding = "2"
base64 = "0.21"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"